apiVersion: apps/v1
kind: Deployment

metadata:
  name: automation-platform
  labels:
    app: automation-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: automation-platform

  template:
    metadata:
      labels:
        app: automation-platform

    spec:
      containers:
      - name: automation-platform-container
        image: 251522454642.dkr.ecr.ap-south-1.amazonaws.com/automation-platform:v21
        envFrom:
          - configMapRef:
              name: automation-platform-config

          - secretRef:
              name: automation-platform-secret

        ports:
        - containerPort: 8000